name: Test

on:
  pull_request:
  workflow_call:

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true
      - name: Setup DB
        run: bin/rails db:setup && bin/rails db:migrate
      - name: Build assets
        run: RAILS_ENV=test bin/rails assets:precompile
      - name: Run all tests
        run: bin/rspec --format=progress
